//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourDictionaryLibrary_Dat_Tan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int Id { get; set; }
        public string English_Word { get; set; }
        public string Word_Type { get; set; }
        public string Phonetic { get; set; }
        public string Meaning { get; set; }
    }
}
